carts/urls.py
from django.urls import path

from . import views

app_name = "carts"

urlpatterns = [
    path("", views.cart, name="cart"),
    path(
        "add/<int:product_id>/", views.add_to_cart, name="add_to_cart"
    ),  # for function based view
    # path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'), # for class based view
    path(
        "remove/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_quantity,
        name="remove_cart_quantity",
    ),  # for function based view
    path(
        "remove-cart-item<int:product_id>/<int:cart_item_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),  # for function based view
    path("checkout/", views.checkout, name="checkout"),
]

greatKart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("securelogin/", admin.site.urls),
    path("", views.ProductListView.as_view(), name="home"),
    #  path('',views.home,name='home'),
    path("store/", include("store.urls")),
    path("cart/", include("carts.urls")),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = "orders"

urlpatterns = [
    path("order_place", views.order_place, name="order_place"),
    path("payments/", views.payments, name="payments"),
    path("payments/sslc/status", views.payment_status, name="payment_status"),
    path("payments/sslc/order_complete/", views.order_complete, name="order_complete"),
]

store/urls.py
from django.urls import path

from store import views

app_name = "store"
urlpatterns = [
    path("", views.StoreView.as_view(), name="store"),
    # path('', views.store, name='store'),
    path(
        "category/<slug:category_slug>/",
        views.StoreView.as_view(),
        name="product_by_category",
    ),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    # path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path("search/", views.search, name="search"),  # funtion based view
    path("search/", views.ProductSearchView.as_view(), name="search"),
    path("submit_review/<int:product_id>/", views.submit_review, name="submit_review"),
]

carts/models.py
from django.db import models

from accounts.models import CustomUser
from store.models import Product, Variation


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True, blank=True
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name="cart_items", null=True, blank=True
    )
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.product_name

carts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from store.models import Product, Variation

from .models import Cart, CartItem


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return cart


# def _cart_id(request):
#     cart_id = request.session.session_key
#     if not cart_id:
#         request.session.create()
#         cart_id = request.session.session_key
#     return cart_id


def add_to_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    if current_user.is_authenticated:
        product_variation = []
        if request.method == "POST":
            for item in request.POST:
                key = item
                value = request.POST.get(key)
                try:
                    variation = Variation.objects.get(
                        product=product,
                        variation_category__iexact=key,
                        variation_value__iexact=value,
                    )
                    product_variation.append(variation)
                except Variation.DoesNotExist:
                    variation = None

        print(product_variation)

        is_cart_item_exists = CartItem.objects.filter(
            product=product, user=current_user
        ).exists()

        # Check if the product already exists in the cart
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            # existing_variations -> database
            # current_variation -> product_variation
            # item_id -> database

            for item in cart_item:
                existing_variation = list(item.variation.all())
                existing_variation_sorted = sorted(
                    existing_variation, key=lambda x: x.id
                )
                product_variation_sorted = sorted(product_variation, key=lambda x: x.id)

                if existing_variation_sorted == product_variation_sorted:
                    item.quantity += 1
                    item.save()
                    break

                else:
                    # No matching variation, create new cart item
                    new_item = CartItem.objects.create(
                        product=product, quantity=1, user=current_user
                    )
                    if product_variation:
                        new_item.variation.set(product_variation)
                    new_item.save()

        else:
            # No item exists at all, create new
            cart_item = CartItem.objects.create(
                product=product, quantity=1, user=current_user
            )
            if product_variation:
                cart_item.variation.set(product_variation)
            cart_item.save()

        return redirect("carts:cart")

    else:
        product_variation = []
        if request.method == "POST":
            for item in request.POST:
                key = item
                value = request.POST.get(key)
                try:
                    variation = Variation.objects.get(
                        product=product,
                        variation_category__iexact=key,
                        variation_value__iexact=value,
                    )
                    product_variation.append(variation)
                except Variation.DoesNotExist:
                    variation = None

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart.save()
        print(product_variation)

        is_cart_item_exists = CartItem.objects.filter(
            product=product, cart=cart
        ).exists()

        # Check if the product already exists in the cart
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing_variations -> database
            # current_variation -> product_variation
            # item_id -> database

            for item in cart_item:
                existing_variation = list(item.variation.all())
                existing_variation_sorted = sorted(
                    existing_variation, key=lambda x: x.id
                )
                product_variation_sorted = sorted(product_variation, key=lambda x: x.id)

                if existing_variation_sorted == product_variation_sorted:
                    item.quantity += 1
                    item.save()
                    break

                else:
                    # No matching variation, create new cart item
                    new_item = CartItem.objects.create(
                        product=product, quantity=1, cart=cart
                    )
                    if product_variation:
                        new_item.variation.set(product_variation)
                    new_item.save()

        else:
            # No item exists at all, create new
            cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if product_variation:
                cart_item.variation.set(product_variation)
            cart_item.save()

        return redirect("carts:cart")


def remove_cart_quantity(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(
                product=product, user=request.user, id=cart_item_id
            )
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(
                product=product, cart=cart, id=cart_item_id
            )

        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except CartItem.DoesNotExist:
        pass
    return redirect("carts:cart")


def remove_cart_item(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(
            product=product, user=request.user, id=cart_item_id
        )
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect("carts:cart")


class AddToCartView(View):
    def get_cart_id(self, request):
        cart_id = request.session.session_key
        if not cart_id:
            cart_id = request.session.create()
        return cart_id

    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)

        cart_id = self.get_cart_id(request)

        cart, created = Cart.objects.get_or_create(cart_id=cart_id)

        cart_item, created = CartItem.objects.get_or_create(product=product, cart=cart)
        if not created:
            cart_item.quantity += 1
        cart_item.save()

        return redirect("carts:cart")

    # def post(self, request, product_id):
    #     self.add_to_cart(request, product_id)
    #     return redirect('carts:cart')

    # def get(self, request, product_id):
    #     self.add_to_cart(request, product_id)
    #     return redirect('carts:cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
    except Cart.DoesNotExist:
        cart_items = []
        total = 0
        quantity = 0
    tax = total * 0.2
    grand_total = total + tax
    context = {
        "cart_items": cart_items,
        "total": total,
        "quantity": quantity,
        "tax": tax,
        "grand_total": grand_total,
    }
    return render(request, "carts/cart.html", context=context)


@login_required
def checkout(request):
    try:
        total = 0
        quantity = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            quantity += cart_item.quantity
    except Cart.DoesNotExist:
        cart_items = []
        total = 0
        quantity = 0
    tax = total * 0.2
    grand_total = total + tax
    context = {
        "cart_items": cart_items,
        "total": total,
        "quantity": quantity,
        "tax": tax,
        "grand_total": grand_total,
    }
    return render(request, "carts/checkout.html", context=context)

carts/templates/carts/cart.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<section class="section-content padding-y bg">
    <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->

    {% if not cart_items %}
      <h2 class="text-center">Your Shopping is Cart Empty</h2>
      <br>
      <div class="text-center">
        <a href="{% url "store:store" %}" class="btn btn-primary">Continue Shopping</a>
      </div>


    {% else %}

        <div class="row">
            <aside class="col-lg-9">
        <div class="card">
        <table class="table table-borderless table-shopping-cart">
        <thead class="text-muted">
        <tr class="small text-uppercase">
        <th scope="col">Product</th>
        <th scope="col" width="120">Quantity</th>
        <th scope="col" width="120">Price</th>
        <th scope="col" class="text-right" width="200"> </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item  in cart_items %}
        <tr>
            <td>
                <figure class="itemside align-items-center">
                    <div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
                    <figcaption class="info">
                        <a href="{{cart_item.product.get_url}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                        <p class="text-muted small">
                            {% if cart_item.variation.all %}
                            {% for i in cart_item.variation.all %}
                            {{i.variation_category | capfirst }}: {{i.variation_value | capfirst}} <br>

                            {% endfor %}

                            {% endif %}
                        </p>
                    </figcaption>
                </figure>
            </td>
            <td>
                <!-- col.// -->
                            <div class="col">
                                <div class="input-group input-spinner">
                                    <div class="input-group-prepend">
                                    <a href="{% url "carts:remove_cart_quantity" cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                    </div>
                                    <input type="text" class="form-control"  value="{{cart_item.quantity}}">

                                    <div class="input-group-append">
                                      <form action="{% url "carts:add_to_cart" cart_item.product.id %}" method="POST">
                                        {% csrf_token %}
                                        {% for item in cart_item.variation.all %}
                                        <input type="hidden" name="{{item.variation_category | lower }}" value="{{item.variation_value | capfirst }}">

                                        {% endfor %}
                                        <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                    </form>
                                    </div>
                                </div> <!-- input-group.// -->
                            </div> <!-- col.// -->
            </td>
            <td>
                <div class="price-wrap">
                    <var class="price">${{cart_item.sub_total}}</var>
                    <small class="text-muted"> ${{cart_item.product.price}} each </small>
                </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right">
                <a href="{% url 'carts:remove_cart_item' cart_item.product.id cart_item.id %}"
                class="btn btn-danger"
                onclick="return confirm('Are you sure you want to delete this item?')">
                Remove
             </a>

            </td>
        </tr>
        {% endfor %}


        </tbody>
        </table>
        </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                    <dt>Total price:</dt>
                    <dd class="text-right">${{total}}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt>Tax:</dt>
                    <dd class="text-right"> ${{tax}}</dd>
                    </dl>
                    <dl class="dlist-align">
                    <dt> Grand Total:</dt>
                    <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                    </dl>
                    <hr>
                    <p class="text-center mb-3">
                        <img src="{% static "./images/misc/payments.png" %}" height="26">
                    </p>
                    <a href="{% url "carts:checkout" %}" class="btn btn-primary btn-block"> Checkout </a>
                    <a href="{% url "store:store" %}" class="btn btn-light btn-block">Continue Shopping</a>
                </div> <!-- card-body.// -->
                </div> <!-- card.// -->

        </aside> <!-- col.// -->


        </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    {% endif %}

    </div> <!-- container .//  -->
    </section>

{% endblock %}

carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->

<div class="row">
	<aside class="col-lg-6">
<div class="card">
  <div class="card-body">
    <h4 class="card-title mb-4">Billing Address</h4>
    <form action="{% url "orders:order_place" %}" method="POST">
      {% csrf_token %}
      <div class="form-row">
        <div class="col form-group">
          <label for="">First Name</label>
          <input type="text" name="first_name" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Last Name</label>
          <input type="text" name="last_name" class="form-control" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <label for="">Email</label>
          <input type="email" name="email" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Phone Number</label>
          <input type="text" name="phone" class="form-control" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <label for="">Address Line 1</label>
          <input type="text" name="address_line_1" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Address Line 2</label>
          <input type="text" name="address_line_2" class="form-control">
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <label for="">City</label>
          <input type="text" name="division" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">District</label>
          <input type="text" name="district" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Country</label>
          <input type="text" name="country" class="form-control" required>
        </div>
        </div>
        <div class="form-row">
          <label for="">Order Note</label>
          <textarea name="order_note" rows="2" class="form-control"></textarea>
        </div>


  </div>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-6">

		<div class="card">
		<div class="card-body">
      <table class="table table-borderless table-shopping-cart">
      <thead class="text-muted">
      <tr class="small text-uppercase">
        <th scope="col">Product</th>
        <th scope="col" width="120">Quantity</th>
        <th scope="col" width="120">Price</th>

      </tr>
      </thead>
      <tbody>

      {% for cart_item in cart_items %}
      <tr>
      	<td>
      		<figure class="itemside align-items-center">
      			<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
      			<figcaption class="info">
      				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
      				<p class="text-muted small">
      					{% if cart_item.variations.all %}
      						{% for item in cart_item.variations.all %}
      							{{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
      						{% endfor %}
      					{% endif %}
      				</p>
      			</figcaption>
      		</figure>
      	</td>
      	<td>
      		<!-- col.// -->
      				<label for="">{{cart_item.quantity}}</label>
      	</td>
      	<td>
      		<div class="price-wrap">
      			<var class="price">$ {{ cart_item.sub_total }}</var>
      			<small class="text-muted"> $ {{ cart_item.product.price }} each </small>
      		</div> <!-- price-wrap .// -->
      	</td>

      </tr>
      {% endfor %}

      </tbody>
      </table>

      <button type="submit" name="submit" class="btn btn-primary btn-block">Place Order</button>
			<a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
      </form>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->


</aside> <!-- col.// -->


</div> <!-- row.// -->

<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}