accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path(
        "activate/<uidb64>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate",
    ),
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("forgot-password/", views.ForgotPassword.as_view(), name="forgot-password"),
    path(
        "password-reset-validate/<uidb64>/<token>/",
        views.ResetPasswordValidate.as_view(),
        name="password-reset-validate",
    ),
    path("reset-password", views.ResetPassword.as_view(), name="reset-password"),
    path("my-orders/", views.MyOrdersView.as_view(), name="my-orders"),
    path("edit-profile/", views.EditProfileView.as_view(), name="edit-profile"),
    path(
        "change-password/", views.ChangePasswordView.as_view(), name="change-password"
    ),
    path(
        "order-detail/<str:order_number>/",
        views.OrderDetailView.as_view(),
        name="order-detail",
    ),
]

carts/urls.py
from django.urls import path

from . import views

app_name = "carts"

urlpatterns = [
    path("", views.cart, name="cart"),
    path(
        "add/<int:product_id>/", views.add_to_cart, name="add_to_cart"
    ),  # for function based view
    # path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'), # for class based view
    path(
        "remove/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_quantity,
        name="remove_cart_quantity",
    ),  # for function based view
    path(
        "remove-cart-item<int:product_id>/<int:cart_item_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),  # for function based view
    path("checkout/", views.checkout, name="checkout"),
]

greatKart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("securelogin/", admin.site.urls),
    path("", views.ProductListView.as_view(), name="home"),
    #  path('',views.home,name='home'),
    path("store/", include("store.urls")),
    path("cart/", include("carts.urls")),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms

from .models import CustomUser, UserProfile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        ),
        label="Password",
    )
    confirm_password = forms.CharField(
        max_length=128,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirm Password", "class": "form-control"}
        ),
        label="Confirm Password",
    )

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "email", "phone_number"]
        widgets = {
            "first_name": forms.TextInput(
                attrs={"placeholder": "First Name", "class": "form-control"}
            ),
            "last_name": forms.TextInput(
                attrs={"placeholder": "Last Name", "class": "form-control"}
            ),
            "email": forms.EmailInput(
                attrs={"placeholder": "Email", "class": "form-control"}
            ),
            "phone_number": forms.TextInput(
                attrs={"placeholder": "Phone Number", "class": "form-control"}
            ),
        }

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists.")
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password and confirm_password and password != confirm_password:
            self.add_error("confirm_password", "Passwords do not match.")
        return cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("first_name", "last_name", "phone_number")

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"


class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(
        required=False,
        error_messages={"invalid": ("Image files only")},
        widget=forms.FileInput,
    )

    class Meta:
        model = UserProfile
        fields = (
            "address_line_1",
            "address_line_2",
            "division",
            "district",
            "country",
            "profile_picture",
        )

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

accounts/views.py
import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, TemplateView

from orders.models import Order

from .forms import RegistrationForm, UserForm, UserProfileForm
from .models import CustomUser, UserProfile

User = get_user_model()
from carts.models import Cart, CartItem
from carts.views import _cart_id
from orders.models import OrderProduct


# Create your views here.
class RegisterView(CreateView):
    template_name = "accounts/register.html"
    form_class = RegistrationForm
    success_url = reverse_lazy("accounts:login")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = form.cleaned_data["email"].split("@")[0]
        user.set_password(form.cleaned_data["password"])
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)
        activation_link = (
            f"http://{current_site.domain}/accounts/activate/{uid}/{token}/"
        )
        subject = "Activate your account"
        message = render_to_string(
            "accounts/account_verification_email.html",
            {
                "user": user,
                "activation_link": activation_link,
            },
        )

        to_email = user.email
        email = EmailMessage(subject, message, settings.DEFAULT_FROM_EMAIL, [to_email])
        email.send()

        # messages.success(self.request, "An email has been sent. Please check your inbox to activate your account.")
        return redirect(f"/accounts/login/?command=verification&email={to_email}")


class ActivateAccountView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            print("User is_active:", user.is_active)
            messages.success(request, "Your account has been activated successfully.")
            return redirect("accounts:login")
        else:
            print("User is_active:", user.is_active)
            messages.error(request, "Activation link is invalid or has expired.")
            return redirect("accounts:register")


class LoginView(View):
    template_name = "accounts/login.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(request, email=email, password=password)

        if user is not None:
            old_cart_id = _cart_id(request)
            login(request, user)

            try:
                cart = Cart.objects.get(cart_id=old_cart_id)
                guest_cart_items = CartItem.objects.filter(cart=cart, user=None)

                for guest_item in guest_cart_items:
                    guest_variations = list(guest_item.variation.all())

                    # Check if user already has this product + variation
                    existing_items = CartItem.objects.filter(
                        user=user, product=guest_item.product
                    )
                    found_match = False

                    for existing_item in existing_items:
                        existing_variations = list(existing_item.variation.all())

                        if sorted(guest_variations, key=lambda x: x.id) == sorted(
                            existing_variations, key=lambda x: x.id
                        ):
                            # Merge: Increase quantity
                            existing_item.quantity += guest_item.quantity
                            existing_item.save()
                            found_match = True
                            break

                    if not found_match:
                        # Assign guest item to user
                        guest_item.user = user
                        guest_item.save()

            except Cart.DoesNotExist:
                print("No guest cart found")

            messages.success(request, "Login successful.")
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split("=") for x in query.split("&"))
                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            except:
                return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid login credentials")
            return redirect("accounts:login")


class CustomLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, "Logout successful.")
        return redirect("home")


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        orders = Order.objects.filter(
            user_id=self.request.user.id, is_ordered=True
        ).order_by("-created_at")
        context["orders"] = orders
        context["orders_count"] = orders.count()
        context["userprofile"] = get_object_or_404(
            UserProfile, user_id=self.request.user.id
        )
        return context


class MyOrdersView(LoginRequiredMixin, ListView):
    model = Order
    template_name = "accounts/my_order.html"
    context_object_name = "orders"

    def get_queryset(self):
        return Order.objects.filter(
            user_id=self.request.user.id, is_ordered=True
        ).order_by("-created_at")


class EditProfileView(LoginRequiredMixin, View):
    template_name = "accounts/edit_profile.html"

    def get(self, request):
        userprofile = get_object_or_404(UserProfile, user=request.user)
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
        context = {
            "user_form": user_form,
            "profile_form": profile_form,
            "userprofile": userprofile,
        }
        print(f"userprofile {userprofile.profile_picture.url}")
        return render(request, self.template_name, context)

    def post(self, request):
        userprofile = get_object_or_404(UserProfile, user=request.user)

        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile has been updated successfully.")
            return redirect("accounts:dashboard")
        else:
            messages.error(request, "Please correct the error below.")
            context = {
                "user_form": user_form,
                "profile_form": profile_form,
                "userprofile": userprofile,
            }
            return render(request, self.template_name, context)


class ChangePasswordView(LoginRequiredMixin, View):
    template_name = "accounts/change_password.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        current_password = request.POST.get("current_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")

        user = CustomUser.objects.get(username__exact=request.user.username)
        if new_password == confirm_password:
            success = user.check_password(current_password)
            if success:
                user.set_password(confirm_password)
                user.save()
                messages.success(request, "Password updated successfully.")
                return redirect("accounts:change-password")
            else:
                messages.error(request, "Please enter valid current password")
                return redirect("accounts:change-password")
        else:
            messages.error(request, "Password does not match!")
            return redirect("accounts:change-password")


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "accounts/order_detail.html"
    context_object_name = "order"
    slug_field = "order_number"
    slug_url_kwarg = "order_number"

    def get_object(self):
        order_number = self.kwargs.get("order_number")
        return get_object_or_404(Order, order_number=order_number)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.get_object()
        order_detail = OrderProduct.objects.filter(order=order)
        subtotal = 0
        for item in order_detail:
            subtotal += item.product_price * item.quantity
        context["order_detail"] = order_detail

accounts/templates/accounts/account_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to confirm your registration.
{% comment %} http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %} {% endcomment %}
 {{activation_link}}

If you think it's not you, please ignore this email.

{% endautoescape %}

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Change Your Password</strong>

		</header>
		<div class="card-body">
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'accounts:change-password' %}" method="POST">
					{% csrf_token %}

					<div class="form-group">
						<label>Current Password</label>
						<input type="password" name="current_password" placeholder="Current Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Create new password</label>
						<input type="password" name="new_password" placeholder="Create New Password" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Confirm new password</label>
						<input type="password" name="confirm_password" placeholder="Confirm New Password" class="form-control" required>
					</div>

					<input type="submit" value="Submit" class="btn btn-primary">
				</form>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% comment %} {% include 'includes/alerts.html' %} {% endcomment %}
<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as:</strong>
			<span>{{user.full_name}}</span>
		</header>
		<div class="card-body">
			<div class="row">

			<div class="col-md-6">
				<div class="card" style="text-align:center;">
					<div class="card-body">
						<h5 class="card-title">Total Orders</h5>
						<h4>{{orders_count}}</h4>
						<a href="{% url 'accounts:my-orders' %}">View Orders</a>

					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card" style="text-align:center;">
					<div class="card-body">
						<img src="{{userprofile.profile_picture.url}}" alt="User Profile Picture" width="50" height="50" style="border-radius:50%;">
						<p class="mb-0">{{user.email}}</p>
						<p>{{user.phone_number}}</p>
					</div>
				</div>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit your profile</strong>

		</header>
		<div class="card-body">
			<div class="text-right">
				<img src="{{userprofile.profile_picture.url}}" alt="Profile Picture" width="100" style="border-radius:50px;">
			</div>
			<div class="row">
			<div class="col-md-12">
				<form action="{% url 'accounts:edit-profile' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>First Name</label>
							{{user_form.first_name}}
						</div>
						<div class="form-group col-md-6">
							<label>Last Name</label>
							{{user_form.last_name}}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Phone Number</label>
							{{user_form.phone_number}}
						</div>
						<div class="form-group col-md-6">
							<label>Profile Picture</label>
							{{profile_form.profile_picture}}
						</div>
					</div>
					<div class="form-group">
						<label>Address Line 1</label>
						{{profile_form.address_line_1}}
					</div>
					<div class="form-group">
						<label>Address Line 2</label>
						{{profile_form.address_line_2}}
					</div>
					<div class="form-row">
						<div class="form-group col-md-4">
							<label>City</label>
							{{profile_form.division}}
						</div>
						<div class="form-group col-md-4">
							<label>District</label>
							{{profile_form.district}}
						</div>
						<div class="form-group col-md-4">
							<label>Country</label>
							{{profile_form.country}}
						</div>
					</div>
					<input type="submit" value="Save" class="btn btn-primary">
				</form>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

accounts/templates/accounts/forgot_password.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

        <!-- ============================ COMPONENT LOGIN   ================================= -->
            <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            <div class="card-body">
                {% include "includes/alerts.html" %}
            <h4 class="card-title mb-4">Forgot Password</h4>
            <form action="{% url 'accounts:forgot-password' %}" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email Address" name='email' >
                </div> <!-- form-group// -->


                <div class="form-group">
                    <a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a>

                </div> <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Submit </button>
                </div> <!-- form-group// -->
            </form>
            </div> <!-- card-body.// -->
            </div> <!-- card .// -->

            <p class="text-center mt-4">Don't have account? <a href="{% url "accounts:register" %}">Sign up</a></p>
            <br><br>
        <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


        </section>
        <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">
    {% if request.GET.command == 'verification' %}

        <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
        Thank you for registering with us. We have sent you a verification email to your email address [{{ request.GET.email }}]
        <br><br>
        Already verified? <a href="{% url 'accounts:login' %}">Login</a>
        </div>
    {% else %}
        <!-- ============================ COMPONENT LOGIN   ================================= -->
            <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            <div class="card-body">
                {% include "includes/alerts.html" %}
            <h4 class="card-title mb-4">Sign in</h4>
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email Address" name='email' >
                </div> <!-- form-group// -->
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" name='password' >
                </div> <!-- form-group// -->

                <div class="form-group">
                    <a href="{% url "accounts:forgot-password" %}" class="float-right">Forgot password?</a>

                </div> <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                </div> <!-- form-group// -->
            </form>
            </div> <!-- card-body.// -->
            </div> <!-- card .// -->

            <p class="text-center mt-4">Don't have account? <a href="{% url "accounts:register" %}">Sign up</a></p>
            <br><br>
        <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}

        </section>
        <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

accounts/templates/accounts/my_order.html
{% extends 'base.html' %}


{% block content %}

<section class="section-conten padding-y bg">

{% include 'includes/alerts.html' %}
<div class="container">
	<div class="row">
     {% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Your order history</strong>

		</header>
		<div class="card-body">
			<div class="row">
			<div class="col-md-12">
				<table class="table table-hover">
				  <thead>
				    <tr>
				      <th scope="col">Order #</th>
				      <th scope="col">Billing Name</th>
				      <th scope="col">Phone</th>
				      <th scope="col">Order Total</th>
							<th scope="col">Date</th>
				    </tr>
				  </thead>
				  <tbody>
						{% for order in orders %}
				    <tr>
				     <th scope="row"><a href="{% url 'accounts:order-detail' order.order_number %} ">{{order.order_number}}</a></th>

				      <td>{{order.full_name}}</td>
				      <td>{{order.phone}}</td>
				      <td>${{order.order_total}}</td>
							<td>{{order.created_at}}</td>
				    </tr>
				{% endfor %}

				  </tbody>
				</table>
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            {% include "includes/alerts.html" %}
            <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
            <form action="{% url 'accounts:register' %}" method="POST">
                {% csrf_token %}


                    <div class="form-row">
                        <div class="col form-group">
                            <label>First name</label>
                              {{form.first_name}}
                        </div> <!-- form-group end.// -->
                        <div class="col form-group">
                            <label>Last name</label>
                              {{form.last_name}}
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row end.// -->

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Email</label>
                            {{form.email}}
                            <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </div> <!-- form-group end.// -->
                        <div class="form-group col-md-6">
                            <label>Phone</label>
                            {{form.phone_number}}
                        </div> <!-- form-group end.// -->
                    </div>

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Password</label>
                            {{form.password}}
                        </div> <!-- form-group end.// -->
                        <div class="form-group col-md-6">
                            <label>Confirm password</label>
                            {{form.confirm_password}}
                        </div> <!-- form-group end.// -->
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
                    </div> <!-- form-group// -->
                        {{form.errors}}
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url "accounts:login" %}">Log In</a></p>
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->


    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

        <!-- ============================ COMPONENT LOGIN   ================================= -->
            <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
            <div class="card-body">
                {% include "includes/alerts.html" %}
            <h4 class="card-title mb-4">Reset Password</h4>
            <form action="{% url 'accounts:reset-password' %}" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Email Address" name='password' >
                </div> <!-- form-group// -->
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" name='confirm_password' >
                </div> <!-- form-group// -->

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Reset  </button>
                </div> <!-- form-group// -->

            </form>
            </div> <!-- card-body.// -->
            </div> <!-- card .// -->

            <p class="text-center mt-4">Don't have account? <a href="{% url "accounts:register" %}">Sign up</a></p>
            <br><br>
        <!-- ============================ COMPONENT LOGIN  END.// ================================= -->


        </section>
        <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click below link to reset your password.
{{activation_link}}

If you think it's not you, please ignore this email.

{% endautoescape %}