accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path(
        "activate/<uidb64>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate",
    ),
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("forgot-password/", views.ForgotPassword.as_view(), name="forgot-password"),
    path(
        "password-reset-validate/<uidb64>/<token>/",
        views.ResetPasswordValidate.as_view(),
        name="password-reset-validate",
    ),
    path("reset-password", views.ResetPassword.as_view(), name="reset-password"),
    path("my-orders/", views.MyOrdersView.as_view(), name="my-orders"),
    path("edit-profile/", views.EditProfileView.as_view(), name="edit-profile"),
    path(
        "change-password/", views.ChangePasswordView.as_view(), name="change-password"
    ),
    path(
        "order-detail/<str:order_number>/",
        views.OrderDetailView.as_view(),
        name="order-detail",
    ),
]

carts/urls.py
from django.urls import path

from . import views

app_name = "carts"

urlpatterns = [
    path("", views.cart, name="cart"),
    path(
        "add/<int:product_id>/", views.add_to_cart, name="add_to_cart"
    ),  # for function based view
    # path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'), # for class based view
    path(
        "remove/<int:product_id>/<int:cart_item_id>/",
        views.remove_cart_quantity,
        name="remove_cart_quantity",
    ),  # for function based view
    path(
        "remove-cart-item<int:product_id>/<int:cart_item_id>",
        views.remove_cart_item,
        name="remove_cart_item",
    ),  # for function based view
    path("checkout/", views.checkout, name="checkout"),
]

greatKart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", include("admin_honeypot.urls", namespace="admin_honeypot")),
    path("securelogin/", admin.site.urls),
    path("", views.ProductListView.as_view(), name="home"),
    #  path('',views.home,name='home'),
    path("store/", include("store.urls")),
    path("cart/", include("carts.urls")),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from store import views

app_name = "store"
urlpatterns = [
    path("", views.StoreView.as_view(), name="store"),
    # path('', views.store, name='store'),
    path(
        "category/<slug:category_slug>/",
        views.StoreView.as_view(),
        name="product_by_category",
    ),
    path(
        "category/<slug:category_slug>/<slug:product_slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    # path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path("search/", views.search, name="search"),  # funtion based view
    path("search/", views.ProductSearchView.as_view(), name="search"),
    path("submit_review/<int:product_id>/", views.submit_review, name="submit_review"),
]

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container mt-2">
            <div class="alert alert-{{ message.tags }}" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <strong>Error:</strong>
                {% endif %}
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
      <a class="list-group-item {% if '/accounts/' == request.path %}active{% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard </a>
      <a class="list-group-item {% if '/my-orders/' in request.path %}active{% endif %}" href="{% url 'accounts:my-orders' %}"> My Orders </a>
      <a class="list-group-item {% if '/edit-profile/' in request.path %}active{% endif %}" href="{% url "accounts:edit-profile" %}"> Edit Profile </a>
      <a class="list-group-item {% if '/change-password/' in request.path %}active{% endif %}" href="{% url "accounts:change-password" %}"> Change Password </a>

    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
    <!--   SIDEBAR .//END   -->
  </aside>

templates/includes/footer.html
{% load static %}
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2025 Company GreatKart </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">writetogreatekart@gmail.com</span>
				<span  class="px-2">+017xxxxxx</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
	$(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.mainImage img').attr('src', $(this).attr("href"));
		})
	})
</script>


</body>
</html>

templates/includes/navbar.html
{% load static %}

<header class="section-header">
    {% comment %} <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>

            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav> {% endcomment %}

    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="{% url "home" %}" class="brand-wrap">
                <img class="logo" src="{% static "./images/logo.png" %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
            <div class="category-wrap dropdown d-inline-block float-right">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-bars"></i> All category
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url "store:store"  %}"> All Products </a>
                    {% for category in category_links %}
                    <a class="dropdown-item" href="{% url "store:product_by_category" category.slug %}"> {{category.category_name}} </a>
                    {% endfor %}
                </div>
            </div>  <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <a href="{% url "store:store" %}" class="btn btn-outline-primary">Store</a>
        <div class="col-lg  col-md-6 col-sm-12 col">
            <form action="{% url "store:search" %}" class="search" method="GET">

                <div class="input-group w-100">
                    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name='keyword'>

                    <div class="input-group-append">
                      <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i>
                      </button>
                    </div>
                </div>
            </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is None %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome guest!</small>
                            <div>
                                <a href="{% url "accounts:login" %}">Sign in</a> <span class="dark-transp"> | </span>
                                <a href="{% url "accounts:register" %}"> Register</a>
                            </div>
                        </div>
                        {% else %}
                        <div class="widget-header">
                            <small class="title text-muted">Welcome {{user.first_name}}</small>
                            <div>
                                <a href="{% url "accounts:logout" %}">Logout</a> <span class="dark-transp"> | </span>
                                <a href="{% url "accounts:dashboard" %}"> Dashboard</a>
                            </div>
                        </div>

                        {% endif %}

                        <a href="{% url "carts:cart" %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{cart_count}}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
    </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->




 </header> <!-- section-header.// -->

templates/includes/pagination.html
{% load static %}


<ul class="pagination">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-left"></i>
            <span class="sr-only">Previous</span>
        </a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ i }}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          <i class="fas fa-angle-right"></i>
          <span class="sr-only">Next</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <i class="fas fa-angle-right"></i>
            <span class="sr-only">Next</span>
        </a>
    </li>
{% endif %}
</ul>